### PR TITLE
New service: runit-usr

### PR DESCRIPTION
**Pull request by necrophcodr**
Usage:
- ln -s /etc/sv/runit-usr /var/service/[someuser]

### CODE REVIEW

**Comment by uggedal** [comment]
Does this need to be packaged? Can't it just be some documentation in the wiki with the 2 line shell/run script as an example?

**Comment by necrophcodr** [comment]
Sure thing, but in that case it would have to be some visible wiki documentation that covers these areas for system administrators, and I'm not sure where that would be. Perhaps documented in https://github.com/voidlinux/documentation/wiki/runit ? Regardless though, I was adviced to post this pull request here, and so I do not know of a better way.

**Comment by chneukirchen** [comment]
Also, as is this does not work because it will use the same supervise/ for multiple users.

**Comment by necrophcodr** [comment]
How so? Does runsvdir not take into account to use the same privileges as it has for the supervise directory? It is only started as $USER for each $USER, so no two users will have the same runsvdir process started for them with the same privileges.

**Comment by chneukirchen** [comment]
```
ln -s /etc/sv/runit-usr /var/service/foo
ln -s /etc/sv/runit-usr /var/service/bar
```

Now foo and bar will have the same supervise/

**Comment by necrophcodr** [comment]
This may fix those issues, but it does add another step (or two, on already-installed systems).

**Comment by necrophcodr** [comment]
This could possibly also be done as a system admin command, but for keeping it permanent, one would need a runit script like these. This may be too trivial though, who knows.

**Comment by Vaelatern** [comment]
Closed with an addition to the FAQ.

**Comment by Vaelatern** [comment]
https://git.io/vdYBS

**Pull request closed without merging**
