### PR TITLE
Fix another always succeeding test

### PR DESCRIPTION
**Pull request by ackalker**

### CODE REVIEW

**Comment by ackalker** [comment]
I'm sorry, missed this one in #60

**Comment by Vaelatern** [comment]
Can we replace the test everywhere with a simple `[ -x /usr/bin/agetty ]` assuming the `/usr/bin` symlinks are not going to go away? Or should we maintain these tests just because somebody (or us) might well want to run a split system some day?

**Comment by Gottox** [comment]
I see no reason why we should split `*/sbin` and `*/bin` again (I'm not sure about `/bin` and `/usr/bin` though)

**Comment by the-maldridge** [comment]
@Vaelatern @Gottox I'm happy with this as it sits, but if you would rather see it with the simplified check then I'll wait to merge for that to go through.

**Pull request merged**
