### PR TITLE
3: Fallback to killall5 if pkill doesn't work as expected

### PR DESCRIPTION
**Pull request by nmeum**
This removes the `procps-ng` dependency and allows us to enable the busybox `ps`, `pkill` and `pgrep` applets in the `base-system-busybox` package. See voidlinux/void-packages#1105.

Maybe this should be documented in the `README` as well?

### CODE REVIEW

**Comment by chneukirchen** [comment]
Ok in principle, but why fall back to killall5 when you just added pkill to busybox?

**Comment by chneukirchen** [comment]
Ok, because busybox pkill doesnt know --inverse. AFAICS it should support -v though (which procps-ng doesnt...)

**Comment by nmeum** [comment]
Yes, it does support `-v` but it doesn't support `-s0,1` you can just specify a single session id with `-s`.

**Comment by chneukirchen** [comment]
Yes, killall5 was from sysvinit.

**Comment by nmeum** [comment]
Yep, so I guess this is probably the best solution to make this thing work with `base-system-busybox`…

**Comment by nmeum** [comment]
I guess it is probably better to check if `killall5` exists, using `test -x $(command -v killall5)` for instance instead of invoking it when `pkill` exists with a non-zero exit status.

**Pull request closed without merging**
