### PR TITLE
3: Detect and deactivate LVM Volume Groups on shutdown

### PR DESCRIPTION
**Pull request by bougyman**

### CODE REVIEW

**Comment by xtraeme** [comment]
Do not put this inside VIRTUALIZATION, it makes no sense.

**Comment by xtraeme** [comment]
My previous comment was wrong... just move this after the existing VIRTUALIZATION, this way there's no need to add another conditional.

**Comment by bougyman** [comment]
It has to be after the sync, though, and I don't think it belongs in the kexec block, but I can move it there if you want it there.

**Comment by bougyman** [comment]
Like this, then?

**Comment by bougyman** [comment]
Tested on two boxes with VGs as well as an lxc and my laptop (btrfs, no VGS). I don't have many test scenarios here.  (no luks)

**Comment by xtraeme** [comment]
Looks ok, thanks :+1:

**Pull request merged**
