### PR TITLE
core-services/01-static-devnodes.sh: Honour modprobe blacklists

### PR DESCRIPTION
**Pull request by dne**

### CODE REVIEW

**Comment by dne** [comment]
Comments, anyone?

The use case here is that I would like to have some way to avoid loading large kernel modules, e.g. btrfs, that I don't use.

**Comment by Gottox** [comment]
I think the problem with this is, that it isn't supported by busybox modprobe. @chneukirchen @Duncaen what do you think?

**Comment by dne** [comment]
Thanks for your comment!

AFAICT, busybox has no "kmod" command applet, so this script wouldn't work anyway?

**Comment by dne** [comment]
Any feedback on my previous comment? Do we need to worry about Busybox support here?

**Comment by the-maldridge** [comment]
Ideally we don't want to lose support for something that works already.  That being said its been a few years since I tried to bring up a system on busybox so I can't vouch that it works at the moment.

Assuming that this script already doesn't run on a busybox system, I have no other issues.

**Comment by dne** [comment]
I note that Busybox modprobe actually does accept "-b" even when the blacklist feature is disabled, as in Void's package.

**Comment by dne** [comment]
Summing up: 
- Busybox has no `kmod` applet, so `kmod static-nodes` is unlikely to yield useful output there.
- Busybox `modprobe` accepts `-b`, even when the blacklist feature is disabled.

Any other reason why this can't be merged?

Thanks!

**Comment by dne** [comment]
How about finally merging this one?

Cheers!

**Comment by Gottox** [comment]
Ah, get this in for now. If we ever support busybox, there may be other things to consider too.

**Pull request merged**
