### PR TITLE
Make crypt.awk work with other awk(1) variants.

### PR DESCRIPTION
**Pull request by suiginsoft**
Change use of the coprocess pipe operator, a GNU extension, to a
regular pipe when reading data back from blkid(8). Since we aren't
piping data to blkid(8) and then reading it back, we only need a
regular pipe and getline here anyway.

Without this change, using mawk(1) as the default awk on Void
results in failure when parsing /etc/crypttab and dumps us to
a rescue shell on boot.

### CODE REVIEW

**Comment by Gottox** [comment]
I'm not an awk expert, but this sounds reasonable. Any further comments?

**Comment by pulux** [comment]
your change failed with:
```/bin/sh: -l: command not found ``` with `mawk`

**Comment by pulux** [comment]
hold on, there are more issuse with mawk.

**Comment by chneukirchen** [comment]
Please try `if (o_src[1] == "UUID") ("blkid -l -o device -t " $2) | getline src;`

**Comment by pulux** [comment]
```("blkid -l -o device -t " $2) | getline src;``` works with all awk's we have

**Comment by suiginsoft** [comment]
Thanks for looking further into this pulux. I'm using mksh instead of dash as my default /bin/sh through xbps-alternatives, hence the reason my original patch seemed to work but doesn't with dash. Do you want to make the submission? I'm not sure why you closed #59 instead of modifying your patch?

**Comment by pulux** [comment]
I closed #59 while is addressed a minor part. The proporsual

**Comment by suiginsoft** [comment]
Okay, I've updated my commit, hopefully this should do it. I've test it out on my machine and it seems to be working great.

**Comment by pulux** [comment]
should be merged

**Comment by suiginsoft** [comment]
Any reason why this hasn't been pulled yet?

**Comment by Gottox** [comment]
There's no other reason than fear. Base software is crucial for void. If boot doesn't work for anyone, void is basicly dead upon the next reboot. :smile:

@chneukirchen can you verifiy if the change is okay? I'm no awk guy, so I can't tell.

**Comment by chneukirchen** [comment]
LGTM.

**Pull request merged**
