### PR TITLE
core-services/00-pseudofs.sh: Add securityfs mountpoint - Needed for …

### PR DESCRIPTION
**Pull request by coredumb**
…LSM support

### CODE REVIEW

**Comment by Vaelatern** [comment]
:shipit:

**Comment by the-maldridge** [comment]
:shipit:

**Comment by coredumb** [comment]
The time has shifted a bit here... 
This could be linked to I guess https://github.com/voidlinux/void-packages/pull/6009/files#diff-7ec1df5055a8b4ba54bfadbfb13371f0

**Comment by ebfe** [comment]
So with #6009 this isn't needed anymore? revert?

**Comment by coredumb** [comment]
It is, but as you said, it may be smarter to make it conditional on rc.apparmor

**Pull request merged**
