### PR TITLE
no --noclear by default

### PR DESCRIPTION
**Pull request by nmeum**
Instead source 'conf' to allow the user to enable it manually.
Furthermore use relative instead of absolut paths for the symlinks (just
in case we change the SVDIR someday).

BTW: `agetty-console` doesn't use `setsid` is this supposed to be the case? Furthermore, `agetty-serial` isn't compatible with `base-system-busybox`. Maybe it would be a good idea to modify `agetty-generic/run` a bit and use it for all ttys (even for console and serial).

### CODE REVIEW

**Comment by xtraeme** [comment]
Why do you remove --noclear? I want it back.

**Comment by nmeum** [comment]
1) `--noclear` is kind a privacy issue because if I log out the screen isn't cleared (by default) and the next users might see sensitive information (emails, passwords, …)

2) `--noclear` isn't available in busybox getty implementations this changes the behavior depending on the base-system you use, which sucks imho.

3) I assume that most users don't want `--noclear` if you do want it you can create a `conf` file in agetty-tty1 and symlink it to agetty-tty[2-6].

**Comment by bougyman** [comment]
I think changing the default behavior on users is generally not a good idea, but I do not like --noclear myself. How about enabling --noclear by default in conf/, making it easy to disable but not changing behavior for current users unless they choose?

**Comment by nmeum** [comment]
The thing is: If you do that it won't work with busyboxs getty implementation. So if you use `base-system-busybox` you need to change that conf file manually. Of cause it would also be possible to check which implementation is available in the conf file but then we would do that check twice (in conf and in run) which sucks.

**Comment by chneukirchen** [comment]
This is getting nowhere. Users with special wishes can easily copy their agetty and make it do whatever they want.

**Pull request closed without merging**
